# This file was generated by GoReleaser. DO NOT EDIT.
cask "csizer" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "edc647edb56ecdc77d7242dc79c85c58127fcf5fba3caa929d75476a25aa3acd"
      url "https://github.com/JJunior19/csizer/releases/download/v#{version}/csizer_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b003b30de8d7e8024eb2115e3625308919abbd7f9e374ea324285eb739573e0c"
      url "https://github.com/JJunior19/csizer/releases/download/v#{version}/csizer_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d41ec4fad1fb471789c35b9136c82034df125e71434674bfadbb947623b74eee"
      url "https://github.com/JJunior19/csizer/releases/download/v#{version}/csizer_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "32775abfa194546c76c60389dcd47cde55f9ff6f037f96ff7e025d0017c7db24"
      url "https://github.com/JJunior19/csizer/releases/download/v#{version}/csizer_#{version}_linux_amd64.tar.gz"
    end
  end

  name "csizer"
  desc "Container workload tracking and ECS Fargate sizing recommendations"
  homepage "https://github.com/JJunior19/csizer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "csizer"

  # No zap stanza required
end
