# This file was generated by GoReleaser. DO NOT EDIT.
cask "csizer" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "cfe31c540d767ac8859b220a57a0e0d8aaa9cf8fd1bf4c82d334e006223ca5ae"
      url "https://github.com/JJunior19/csizer/releases/download/v#{version}/csizer_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "edbec0ccba8860b2ee126c6f1dc2dba02978b48231ba00356b40e76e25bf2d4e"
      url "https://github.com/JJunior19/csizer/releases/download/v#{version}/csizer_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2f0d7a037aad2dd3796966915a51ed4c4490e85f273a47ded8e487e80d35135b"
      url "https://github.com/JJunior19/csizer/releases/download/v#{version}/csizer_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8d0eb104869afe1e5354a925517e8bfe9a1412760e9fe4441c9d7b989e8f13e0"
      url "https://github.com/JJunior19/csizer/releases/download/v#{version}/csizer_#{version}_linux_amd64.tar.gz"
    end
  end

  name "csizer"
  desc "Container workload tracking and ECS Fargate sizing recommendations"
  homepage "https://github.com/JJunior19/csizer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "csizer"

  # No zap stanza required
end
