# This file was generated by GoReleaser. DO NOT EDIT.
cask "csizer" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "4d17f9dd12242429670368324fbbe219b832d113706f919875d0704dc2067b4b"
      url "https://github.com/JJunior19/csizer/releases/download/v#{version}/csizer_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cb1e28b3e76a348d8df130885915c6524233a0547c8869e35cddc6561b5a5753"
      url "https://github.com/JJunior19/csizer/releases/download/v#{version}/csizer_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f1781e5cb60a444e6aaf5ed1ac0fb6046623a8c0c0e9dddd1cad053c5817280a"
      url "https://github.com/JJunior19/csizer/releases/download/v#{version}/csizer_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c03f94decb12611f3300a8c171a38abd02493d0c6cc24fc302ac922f98c01e42"
      url "https://github.com/JJunior19/csizer/releases/download/v#{version}/csizer_#{version}_linux_amd64.tar.gz"
    end
  end

  name "csizer"
  desc "Container workload tracking and ECS Fargate sizing recommendations"
  homepage "https://github.com/JJunior19/csizer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "csizer"

  # No zap stanza required
end
